### ISSUE TITLE
Update export/import to provenance redesign

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2342]
We should check that export/import does the right thing after the provenance redesign. Also, the schema version has been upped to `v0.4` and so a migration for `v0.3` archives should be implemented.

- [x] Check that export/import works correctly and respects provenance redesign rules
    * Find at which point the archive version was updated to `v0.3`
    * Determine what the database schema version was at that point
    * Look at all the database migrations that have been applied since, and make a list of what should affect the export archives
    * The cumulative changes should be defined in a migration that can be applied to an archive of `v0.3` to update it to `v0.4`.
- [x] Re-enable `verdi export create`
- [x] Implement migration of `v0.3 -> v0.4` archives will be done in a separate issue (see #2426)
- [x] Re-enable all skipped unittests (see #2426)
- [x] Migrate test fixture archives (see #2426)

**Comment by CasperWA** [comment]
Import/export tests for updated db schema introduced by db migrations since v0.3 are available in branch [`fix_2342_update_export_import_to_prov_redesign`](https://github.com/aiidateam/aiida_core/tree/fix_2342_update_export_import_to_prov_redesign).

Furthermore, I have cleaned up the `export_and_import.py` test file a bit, moving tests into more-or-less relevant test classes.

**NOTE**: This does not fix #2342, since this also calls for writing a migration for an exported file from v0.3 to v0.4. As discussed with @sphuber and @szoupanos, this will not be implemented at this point.

Some tests in `TestLinks` have been removed, since they duplicate existing tests.

**[WIP]**: Other test classes will be rifled through and its tests weighed concerning duplication, with the attempt to streamline the test file further.

**Comment by sphuber** [comment]
Closed in #2554
