### ISSUE TITLE
TRACKER: Python 3 compatibility

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#804]
For Python 3 compatibility we probably want additional bugs per explicit task/issue. This bug will collect discussion/decisions around the Python 3 compatibility efforts.

Feel free to convert this to a project or a milestone at any point.

**Comment by dev-zero** [comment]
Besides code compatibility, there may be other issues:

- [ ] Dependencies. Currently only supervisor is unavailable for Python 3, but we can get rid of it as per PR #790 
- [ ] Pickle. If (native) Python Pickles have been used in user data at some point, this must be converted, preferably to a different serialization format
- [ ] Celery Messages. It seems that we are currently using Pickle as serialization format, which should be changed at some point. To do that, one has to make sure that the Celery message queue in the database (remember, we are using the SQLA backend for Celery) is empty. This is a non-issue should we remove Celery (which can again easily be done replacing the calls in `tasks.py` by a async-based approach (since we are not using Celery for actual async operations at the moment)
- [ ] Gradual conversion. To avoid large impact, we could start by gradually converting the source code. The problem here is that people might be unaware of new style and may re-add Python-2 idiosyncrasies. For that we need to add pre-commit hooks or Travis checkers. See also issue #798. As soon as full Python 3 compatibility is reached, this can be dropped since we can have Python 3 Travis tester

**Comment by dev-zero** [comment]
Helpful tools:

- 2to3 ... includes fixers to convert Python 2 code to Python 3 code. Does **not** maintain Python 2 compatibility
- [python-futurize](http://python-future.org/automatic_conversion.html) ... uses 2to3 fixers and others to make code Py-2-and-3 compatible. Uses the Python Future project.
- [python-modernize](https://python-modernize.readthedocs.io)

**Comment by greschd** [comment]
For plugins, we need at least a working Python 3 branch so that plugins can actually test their code.

**Comment by dev-zero** [comment]
@greschd what I meant is that we could make it a requirement for them to run `pylint --py3k` or `python-modernize` which means their plugins would be python-3 ready

**Comment by giovannipizzi** [comment]
Already now we don't support python 2.6 (we have a lot of `"{}".format(xxx)` in the code)
